baseURL: "https://valery1707.name/"
languageCode: "ru-ru"
title: "Вырва Валерий"
theme: "ananke"

metaDataFormat: "yaml"
sectionPagesMenu: "main"

# Pagination
# number of entries per page for archives, tags and categories
# since we don't have list view, recommend a large value
paginate: 20
paginatePath: "page"

# language support # en / zh-tw / other... translations present in i18n/
defaultContentLanguage: "ru"
defaultContentLanguageInSubdir: true

# service plugins
googleAnalytics: "UA-72977219-1"
enableRobotsTXT: true

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  custom_css:
  - css/fonts.css
  - css/theme-fixes.css
  body_classes: "lato bg-near-white"
  favicon: "favicon.ico"
  description: "Valeriy Vyrva home page"
  facebook: "https://facebook.com/valery1707"
  twitter: "https://twitter.com/valeriy1707"
  instagram: ""
  youtube: ""
  github: "https://github.com/valery1707"
  linkedin: ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-black"
  featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2

languages:
  ru:
    params:
      linkedin: https://www.linkedin.com/in/valery1707/ru
    title: Вырва Валерий
    weight: 1
  en:
    params:
      linkedin: https://www.linkedin.com/in/valery1707/en
    title: Valeriy Vyrva
    weight: 2
